name: Check PR and branch

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint task
        run: |
          npm run lint

      - name: Run build task
        run: |
          npm run build
